# Exported from:        http://host.docker.internal:5516/
# Release version:      23.1.0
# Date created:         Tue May 23 09:55:59 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
